[package]
name = "btree_map"
version = "0.1.0"
authors = ["hsz0r <48858918+hsz0r@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.0"